name: 'entsoe'
version: '1.0.0'
config-version: 2

profile: 'entsoe'

model-paths: ["models"]

on-run-start:
  - "SET TimeZone='UTC'"

models:
  entsoe:
    staging:
      +materialized: view
    marts:
      +materialized: table
